#### importing numpy libraby

In [1]:
import numpy as np

#### 2D matrix

In [2]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print('no of dimensions : ',a.ndim)
print('shape of array :   ',a.shape)

[[1 2 3]
 [4 5 6]]
no of dimensions :  2
shape of array :    (2, 3)


#### 3D matrix

In [3]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print()
print('no of dimensions :  ',a.ndim)
print('shape of array :    ',a.shape)
print('size of array :     ',a.size)
print('datatype of array : ',a.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

no of dimensions :   3
shape of array :     (2, 2, 3)
size of array :      12
datatype of array :  int32


#### Generating Zeros

In [4]:
a = np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### linspace

In [5]:
a = np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [6]:
a = np.linspace(0,1)
a

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

#### Identity Matrix

In [7]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Diagonal Matrix

In [8]:
a = np.diag([1,2,3,4]) 
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### Generate random numbers

In [9]:
a = np.random.rand(4)
a

array([0.58702357, 0.10015616, 0.56425222, 0.46943609])

range : 0-1
Positive Number

In [10]:
np.random.randn(4)

array([-0.17828516,  1.09116754,  1.2509531 , -0.01146326])

Whole Number

In [11]:
np.random.randint(low=0, high=9, size=5)

array([7, 8, 0, 3, 7])

#### arange

In [12]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [13]:
a = np.arange(5, dtype='float64')
a

array([0., 1., 2., 3., 4.])

#### Slicing

In [14]:
x = [0,1,2,3,4,5,6,7,8,9,10]
print('x[:4]  :  ',x[:4])
print('x[4:]  :  ',x[4:])
print('x[3:8] :  ',x[3:8])

x[:4]  :   [0, 1, 2, 3]
x[4:]  :   [4, 5, 6, 7, 8, 9, 10]
x[3:8] :   [3, 4, 5, 6, 7]


#### Complex numbers

In [15]:
a = np.array([1+2j, 3+5j])
print(a)
print('type(a) : ',type(a))
print('a.dtype : ',a.dtype)

[1.+2.j 3.+5.j]
type(a) :  <class 'numpy.ndarray'>
a.dtype :  complex128


#### Sum

In [16]:
y = np.array([[1,1],[2,2]])
print(y)

#sum on columns
s = y.sum(axis=0)
print('sum on columns  :  ',s)

#sum on rows
s = y.sum(axis=1)
print('sum on rows  :  ',s)

[[1 1]
 [2 2]]
sum on columns  :   [3 3]
sum on rows  :   [2 4]


#### min, max

In [17]:
x = np.array([2,3,4,1,5])

print(x)
print('max of x  :  ', x.max())
print('index of max of x  :  ', x.argmax())
print('min of x  :  ', x.min())
print('index of min of x  :  ', x.argmin())

[2 3 4 1 5]
max of x  :   5
index of max of x  :   4
min of x  :   1
index of min of x  :   3


### median

In [18]:
np.median(x)

3.0

## Working with dataset

### loading dataset

In [ ]:
import csv
data = np.loadtxt(path)

In [19]:
data = np.array([[ 7.4 , 0.7 , 0.2 ,0.56 , 9.4 , 5. ],
[ 7.8 , 0.88 , 0. , 0.68 , 9.8 , 5. ],
[ 7.8 , 0.76 , 0.04 , 0.65 , 9.8 , 5. ],
[ 6.3 , 0.51 , 0.13 , 0.75 , 11. , 6. ],
[ 5.9 , 0.645, 0.12 ,0.71 , 10.2 , 5. ],
[ 6. , 0.31 , 0.47 , 0.66 , 11. , 6. ]])

In [20]:
data

array([[ 7.4  ,  0.7  ,  0.2  ,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   ,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 ,  0.65 ,  9.8  ,  5.   ],
       [ 6.3  ,  0.51 ,  0.13 ,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 ,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 ,  0.66 , 11.   ,  6.   ]])

In [21]:
print(data.shape)
print(data.ndim)

(6, 6)
2


### slicing dataset

In [22]:
data1 = data[:,:]
data1

array([[ 7.4  ,  0.7  ,  0.2  ,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   ,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 ,  0.65 ,  9.8  ,  5.   ],
       [ 6.3  ,  0.51 ,  0.13 ,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 ,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 ,  0.66 , 11.   ,  6.   ]])

In [23]:
data2 = data[:,:2]  # upto 2 columns
data2

array([[7.4  , 0.7  ],
       [7.8  , 0.88 ],
       [7.8  , 0.76 ],
       [6.3  , 0.51 ],
       [5.9  , 0.645],
       [6.   , 0.31 ]])

In [24]:
data3 = data[:,1:]  # skip first column
data3

array([[ 0.7  ,  0.2  ,  0.56 ,  9.4  ,  5.   ],
       [ 0.88 ,  0.   ,  0.68 ,  9.8  ,  5.   ],
       [ 0.76 ,  0.04 ,  0.65 ,  9.8  ,  5.   ],
       [ 0.51 ,  0.13 ,  0.75 , 11.   ,  6.   ],
       [ 0.645,  0.12 ,  0.71 , 10.2  ,  5.   ],
       [ 0.31 ,  0.47 ,  0.66 , 11.   ,  6.   ]])

In [25]:
data4 = data[:3,:]  # upto first 3 rows 
data4

array([[7.4 , 0.7 , 0.2 , 0.56, 9.4 , 5.  ],
       [7.8 , 0.88, 0.  , 0.68, 9.8 , 5.  ],
       [7.8 , 0.76, 0.04, 0.65, 9.8 , 5.  ]])

In [26]:
data5 = data[5:,:]  # skip first 5 rows
data5

array([[ 6.  ,  0.31,  0.47,  0.66, 11.  ,  6.  ]])

### timeit

To calculate exact execution time we use timeit method

In [27]:
L = range(1000)
%timeit  [i**2 for i in L]

223 µs ± 3.87 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [28]:
a = np.arange(1000)
%timeit a**2

1.5 µs ± 20.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


numpy method taking less time compare to list comprehension